import type { SkillGroup } from "@/types/content";

export const skillGroups: SkillGroup[] = [
  {
    id: "languages",
    label: "Languages",
    icon: "code",
    summary: "Systems and product languages, picked to fit the workload.",
    skills: ["Python", "JavaScript", "TypeScript", "C++", "R", "Rust", "Golang", "SQL"],
  },
  {
    id: "agentic",
    label: "AI & Agentic Systems",
    icon: "brain",
    summary: "Autonomous agents, orchestration graphs and tool-calling protocols.",
    skills: [
      "LangChain",
      "LangGraph",
      "CrewAI",
      "AutoGen",
      "Agent2Agent Protocol",
      "LlamaIndex",
      "Semantic Kernel",
      "MCP",
      "OpenAI Agents SDK",
    ],
  },
  {
    id: "ml",
    label: "ML & Data Science",
    icon: "sparkles",
    summary: "Training, fine-tuning and evaluating models that reach production.",
    skills: [
      "PyTorch",
      "TensorFlow",
      "scikit-learn",
      "Hugging Face Transformers",
      "NumPy",
      "Pandas",
      "Jupyter",
    ],
  },
  {
    id: "mlops",
    label: "MLOps & Model APIs",
    icon: "workflow",
    summary: "Experiment tracking, evaluation harnesses and multi-provider routing.",
    skills: [
      "MLflow",
      "Weights & Biases",
      "OpenAI API",
      "Claude API",
      "Gemini API",
      "DeepSeek",
      "Qwen",
    ],
  },
  {
    id: "vector",
    label: "Vector & Graph Databases",
    icon: "network",
    summary: "Retrieval layers — dense, hybrid and knowledge-graph backed.",
    skills: [
      "Pinecone",
      "Qdrant",
      "Azure Cosmos DB",
      "ChromaDB",
      "Neo4j",
      "Amazon Neptune",
      "Memgraph",
    ],
  },
  {
    id: "cloud",
    label: "Cloud & Infrastructure",
    icon: "cloud",
    summary: "Cloud-native infrastructure, defined in code and shipped continuously.",
    skills: [
      "AWS",
      "Google Cloud (GCP)",
      "Azure",
      "Terraform",
      "Docker",
      "Kubernetes",
      "GitHub Actions",
    ],
  },
  {
    id: "app",
    label: "Frontend & Backend",
    icon: "layers",
    summary: "The product surface — real-time, typed, and built to scale.",
    skills: [
      "React JS",
      "Next JS",
      "Node.js",
      "Express JS",
      "FastAPI",
      "GraphQL",
      "Socket.IO",
    ],
  },
  {
    id: "data",
    label: "Databases & ORMs",
    icon: "database",
    summary: "Relational, document and in-memory stores with typed access layers.",
    skills: [
      "PostgreSQL",
      "MySQL",
      "MongoDB",
      "Redis",
      "Prisma",
      "Sequelize",
      "Mongoose",
      "SQLite",
    ],
  },
];

/** Flat, de-duplicated skill list — used by the command palette search. */
export const allSkills: string[] = Array.from(
  new Set(skillGroups.flatMap((group) => group.skills)),
);
